language: node_js
node_js:
  - v8
  - v7
  - v6
before_install:
    - npm install -g npm
    - npm install -g codecov
    - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
after_success:  npm run coverage
deploy:
  - provider: npm
    skip_cleanup: true
    email: daniel@cherubini.casa
    api_key:
      secure: L6HD8tWjxQCtAnW+fXe3YT0heYX5/a4O2K1lMP+F48ZXYRhtsi0uePOWnCcF9M8f8/0t1vKR6RSx4W+9wI25dtb6kGXhPmrMffHioDlQ7IorPEu9I36LrSzLR8yX2AkuEg8M1f1XjSHQBlfFNKV0db+U+hFG9hScQzOlJEJ5KH8cwTfkNaXT6Co6oLi1k8RyGTIJ14m5RUxqyv8tnrhRYYFXbtPmx038ePLMgfQ9xW0gvPFjOCpl3JlUdwyQLGBgjypLt4MMeNxbUWoPuGSLBxV6masrxagqYYMaW+yFMhWJg7Cks1eERDuKSnp/2wzdnnwHN3wWEz0c7k6DFvmrF64dbLmsdpMvrZpnCIQoNx5Wkm2nTSiLWpcC7vuiswE5XWTMKcITpw6a1oyY8J0Uvt41JxvoNrJAWT6d9OOrOHvUxGPRs6YXjhUm/fslfvE84BMvwSWHah8jGtUxJY7cm7mNOoWGW47WUb424HJ0D2OgTjCHkKlCM6Q8SnJPS80QFN5Xx75P5CxlWnvtn26M00QFlg1YtLrGxw/9pUnemYUukvkzz3Xmu22IfaNnplPVLjKTVD5lVzv5ERHC4VENvdxHxuPh0p2OY3QkVFd9vyK9YqYNrYvQYCuLq+oegquKkxO43ESHFKcDzipUPTxsWAbPHTQ/6i2X7JSbjfRy7P8=
    on:
      all_branches: true
      tags: true
      repo: express-vue/express-vue
addons:
    code_climate:
        repo_token: 308db9eefcafd79785ed545433e7930a43b926b5bdea95014274a4b7ffe4b06b
